## CA1 - Joao Luis Ribeiro Goes - Local Tourism in Republic of Irleand after,during and before Pandemic(Covid-19).

In [2]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings as wr
from sklearn.preprocessing import LabelEncoder
from sklearn import linear_model
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
wr.filterwarnings('ignore')
import datetime

In [3]:
# Importing the dataset
# looking at the dataset
#ASM03 Air and Sea Travel
df = pd.read_csv("ASM03.20261003T131035.csv")
df.head()

,STATISTIC Label,Month,Country,Direction,UNIT,VALUE
0,Air and Sea Travel,2010 January,Great Britain,Arrivals,Thousand,361.5
1,Air and Sea Travel,2010 January,Great Britain,Departures,Thousand,407.6
2,Air and Sea Travel,2010 January,Other UK (1),Arrivals,Thousand,0.9
3,Air and Sea Travel,2010 January,Other UK (1),Departures,Thousand,1.1
4,Air and Sea Travel,2010 January,Belgium,Arrivals,Thousand,12.5

In [36]:
#Return ten random sample row of the DataFrame
df.sample(10)

,STATISTIC Label,Month,Country,Direction,UNIT,VALUE
4692,Air and Sea Travel,2020 November,Italy,Arrivals,Thousand,1.6
5733,Air and Sea Travel,2023 April,Spain,Departures,Thousand,249.1
5767,Air and Sea Travel,2023 May,Germany,Departures,Thousand,93.0
3040,Air and Sea Travel,2017 January,Poland,Arrivals,Thousand,46.5
5725,Air and Sea Travel,2023 April,Great Britain,Departures,Thousand,634.1
2536,Air and Sea Travel,2015 November,Poland,Arrivals,Thousand,41.4
6191,Air and Sea Travel,2024 April,All countries,Departures,Thousand,1738.4
4779,Air and Sea Travel,2021 January,United States,Departures,Thousand,7.2
2778,Air and Sea Travel,2016 June,Germany,Arrivals,Thousand,93.1
2940,Air and Sea Travel,2016 October,Other Europe (34),Arrivals,Thousand,14.2

In [9]:
df.tail(5)

,STATISTIC Label,Month,Country,Direction,UNIT,VALUE
7195,Air and Sea Travel,2026 August,United Arab Emirates,Departures,Thousand,36.6
7196,Air and Sea Travel,2026 August,Other Countries(42),Arrivals,Thousand,78.3
7197,Air and Sea Travel,2026 August,Other Countries(42),Departures,Thousand,68.7
7198,Air and Sea Travel,2026 August,All countries,Arrivals,Thousand,2532.6
7199,Air and Sea Travel,2026 August,All countries,Departures,Thousand,2433.5

## EDA

In [37]:
#Shows the number of records in each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7200 entries, 0 to 7199
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATISTIC Label  7200 non-null   object
 1   Month            7200 non-null   object
 2   Country          7200 non-null   object
 3   Direction        7200 non-null   object
 4   UNIT             7200 non-null   object
 5   VALUE            7196 non-null   float64
dtypes: float64(1), object(5)
memory usage: 337.6+ KB

In [4]:
#Shows the number of rows and columns
df.shape

(7200, 6)

In [55]:
#Shows the number of records in each column

<class 'pandas.core.frame.DataFrame'>
Index: 3600 entries, 0 to 7198
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Month      3600 non-null   object
 1   Country    3600 non-null   object
 2   Direction  3600 non-null   object
 3   UNIT       3600 non-null   object
 4   VALUE      3598 non-null   float64
dtypes: float64(1), object(4)
memory usage: 168.8+ KB

In [42]:
#Info about values like count, mean, standard deviation, minimum and quartiles for each numerical column.
df.describe()

             VALUE
count  3598.000000
mean    148.013257
std     340.131749
min       0.000000
25%      15.000000
50%      40.400000
75%      92.500000
max    2532.600000

In [43]:
#Info about values like count, mean, standard deviation, minimum and quartiles for each numerical column.
df.describe().T

        count        mean         std  min   25%   50%   75%     max
VALUE  3598.0  148.013257  340.131749  0.0  15.0  40.4  92.5  2532.6

In [44]:
#Covert the columns to list
df.columns.tolist()

['Month', 'Country', 'Direction', 'UNIT', 'VALUE']

In [47]:
#Checks for missing values
df.isnull().sum()

Month        0
Country      0
Direction    0
UNIT         0
VALUE        2
dtype: int64

In [73]:
#Checks for duplicates
df.duplicated().sum()

np.int64(0)

In [49]:
(df.isnull().sum()/len(df))*100

Month        0.000000
Country      0.000000
Direction    0.000000
UNIT         0.000000
VALUE        0.055556
dtype: float64

In [5]:
#Shows the columns 
df.columns

Index(['STATISTIC Label', 'Month', 'Country', 'Direction', 'UNIT', 'VALUE'], dtype='str')

In [6]:
#Shows the datatypes
df.dtypes

STATISTIC Label        str
Month                  str
Country                str
Direction              str
UNIT                   str
VALUE              float64
dtype: object

In [8]:
df.nunique(axis = 0)

STATISTIC Label       1
Month               200
Country              18
Direction             2
UNIT                  1
VALUE              2313
dtype: int64

In [11]:
# Drop rows with missing values
df.dropna(inplace=True)

In [12]:
#Remove one column from the DataFrame
df = df.drop("UNIT",axis=1)

In [13]:
#Remove one column from the DataFrame
df = df.drop("STATISTIC Label", axis=1)
df.head()

          Month        Country   Direction  VALUE
0  2010 January  Great Britain    Arrivals  361.5
1  2010 January  Great Britain  Departures  407.6
2  2010 January   Other UK (1)    Arrivals    0.9
3  2010 January   Other UK (1)  Departures    1.1
4  2010 January        Belgium    Arrivals   12.5

In [20]:
#Renaming column value
df = df.rename(columns={"VALUE": "VALUE_in_thousands"})

In [21]:
(df.isnull().sum()/len(df))*100

Month                 0.0
Country               0.0
Direction             0.0
VALUE_in_thousands    0.0
dtype: float64

In [22]:
df.head(10)

          Month        Country   Direction  VALUE_in_thousands
0  2010 January  Great Britain    Arrivals               361.5
1  2010 January  Great Britain  Departures               407.6
2  2010 January   Other UK (1)    Arrivals                 0.9
3  2010 January   Other UK (1)  Departures                 1.1
4  2010 January        Belgium    Arrivals                12.5
5  2010 January        Belgium  Departures                12.5
6  2010 January        Germany    Arrivals                45.3
7  2010 January        Germany  Departures                42.7
8  2010 January          Spain    Arrivals                68.6
9  2010 January          Spain  Departures                64.2

## Label and Enconde

In [23]:
# Preprocessing
# Encoding categorical features
from sklearn.preprocessing import LabelEncoder

le_direction = LabelEncoder()
le_country = LabelEncoder()
df["Direction_Encoding"] = le_direction.fit_transform(df["Direction"])
df["Country_Encoding"] = le_country.fit_transform(df["Country"])

In [24]:
df["Date"] = pd.to_datetime(df["Month"], format="%Y %B")

In [25]:
df["Year"] = df["Date"].dt.year
df["Month_Encoding"] = df["Date"].dt.month

In [26]:
df.head(10)

,Month,Country,Direction,VALUE_in_thousands,Direction_Encoding,Country_Encoding,Date,Year,Month_Encoding
0,2010 January,Great Britain,Arrivals,361.5,0,4,2010-01-01,2010,1
1,2010 January,Great Britain,Departures,407.6,1,4,2010-01-01,2010,1
2,2010 January,Other UK (1),Arrivals,0.9,0,10,2010-01-01,2010,1
3,2010 January,Other UK (1),Departures,1.1,1,10,2010-01-01,2010,1
4,2010 January,Belgium,Arrivals,12.5,0,1,2010-01-01,2010,1
5,2010 January,Belgium,Departures,12.5,1,1,2010-01-01,2010,1
6,2010 January,Germany,Arrivals,45.3,0,3,2010-01-01,2010,1
7,2010 January,Germany,Departures,42.7,1,3,2010-01-01,2010,1
8,2010 January,Spain,Arrivals,68.6,0,14,2010-01-01,2010,1
9,2010 January,Spain,Departures,64.2,1,14,2010-01-01,2010,1

In [27]:
#Check the country with the code
df[['Country', 'Country_Encoding']].head(20)

          Country  Country_Encoding
0   Great Britain                 4
1   Great Britain                 4
2    Other UK (1)                10
3    Other UK (1)                10
4         Belgium                 1
5         Belgium                 1
6         Germany                 3
7         Germany                 3
8           Spain                14
9           Spain                14
10         France                 2
11         France                 2
12          Italy                 5
13          Italy                 5
14    Netherlands                 6
15    Netherlands                 6
16         Poland                11
17         Poland                11
18       Portugal                12
19       Portugal                12

In [28]:
#Only Unique Values
df[['Country', 'Country_Encoding']].drop_duplicates().sort_values('Country_Encoding')

                                              Country  Country_Encoding
34                                      All countries                 0
4                                             Belgium                 1
10                                             France                 2
6                                             Germany                 3
0                                       Great Britain                 4
12                                              Italy                 5
14                                        Netherlands                 6
32                                Other Countries(42)                 7
24                                  Other Europe (34)                 8
28                   Other Transatlantic Countries(1)                 9
2                                        Other UK (1)                10
16                                             Poland                11
18                                           Portugal                12
20  Selected EU (AT,BG,CY,CZ,DK,EE,FI,GR,HR,HU,LT,...                13
8                                               Spain                14
22                                        Switzerland                15
30                               United Arab Emirates                16
26                                      United States                17

In [29]:
#Remove unless data
Trash = [
    'All countries', 
    'Selected EU (AT,BG,CY,CZ,DK,EE,FI,GR,HR,HU,LT,LU,LV,MT,RO,SE,SI,SK)'
]

In [30]:
#The isin() method checks if the Dataframe contains the specified value(s).
#copy()	Return a shallow copy of an object.
df2 = df[~df['Country'].isin(Trash)].copy()

## New Data Frame df2

In [1]:
df2.head(20)

NameError: name 'df2' is not defined

In [ ]:
df2.drop(columns=["Month", "Country", "Date", "Direction"], inplace=True)
df2.head()

In [ ]:
#All columns are numerics
df2.info()

In [ ]:
# Create the independent and dependent variable (Target variable)
# Independent variables
y = df2['VALUE_in_thousands']
# Target variable
X = df2.drop(columns=['VALUE_in_thousands'])
y.head()

In [ ]:
X.head()

In [ ]:
X.info()

In [ ]:
y.info()

In [ ]:
df2.head()

## Split the data into training and testing set